hdfs: namenode component check
TOSIT-IO/tdp-collection pull request #263
Opened 2022-05-12 16:36 UTC by kpgtek

#### Which issue(s) this PR fixes:

Fixes #241

#### Additional comments:

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-05-13 10:22 UTC, rpignolet commented on tdp_vars_defaults/hadoop/hadoop.yml
> +# HDFS component listen port
```suggestion
# HDFS Namenode component listen port
```

2022-05-16 13:52 UTC, leopaul36 commented on tdp_vars_defaults/hadoop/hadoop.yml
> +hdfs_nn_rpc_port: 8020
Shouldn't we parse this from the `dfs.namenode.rpc-address.mycluster.nn` variable?

2022-05-16 17:06 UTC, kpgtek commented on tdp_vars_defaults/hadoop/hadoop.yml
> +hdfs_nn_rpc_port: 8020
We could parse the port number from ```dfs.namenode.rpc-address.mycluster.nn```.
Or could we move ```hdfs_nn_rpc_port:8020``` from ```hadoop.yml``` to ```hdfs.yml```, for futur use (by other service)?

2022-05-17 07:36 UTC, gboutry commented on tdp_vars_defaults/hadoop/hadoop.yml
> +hdfs_nn_rpc_port: 8020
I don't think we should parse these ports, I think it's better to define them as variables in hadoop, it gives us access to these ports easily in other configurations, such as for `knox` where we need to put the ports in conf

2022-05-17 08:28 UTC, rpignolet commented on tdp_vars_defaults/hadoop/hadoop.yml
> +hdfs_nn_rpc_port: 8020
I think we should only put port variable inside `hadoop.yml` when we need it in multiple services. I do not think that Knox need the Namenode RPC port. If a service need it in the futur, we can move the variable from `hdfs.yml` to `hadoop.yml`.

2022-05-19 08:46 UTC, kpgtek commented on tdp_vars_defaults/hadoop/hadoop.yml
> +hdfs_nn_rpc_port: 8020
I think it is more interesting to define explicitly ports variables, if we decide to perform checks on every ports in ```component check```. For the moment, we could "prepare" this by defining them inside each compoment variable file, if needed, we could export them to ```hadoop.yml``` as it is done for ```zookeeper``` (PR #255).

2022-06-03 09:30 UTC, leopaul36 commented
I have an issue with a fresh install with this refactor. Datanodes are unable to start, the error is:

```
2022-06-03 09:27:19,356 ERROR org.apache.hadoop.hdfs.server.datanode.DataNode: Exception in secureMain
java.net.BindException: Problem binding to [0.0.0.0:9867] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:831)
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:736)
        at org.apache.hadoop.ipc.Server.bind(Server.java:562)
        at org.apache.hadoop.ipc.Server$Listener.<init>(Server.java:1038)
        at org.apache.hadoop.ipc.Server.<init>(Server.java:2810)
        at org.apache.hadoop.ipc.RPC$Server.<init>(RPC.java:960)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server.<init>(ProtobufRpcEngine.java:421)
        at org.apache.hadoop.ipc.ProtobufRpcEngine.getServer(ProtobufRpcEngine.java:342)
        at org.apache.hadoop.ipc.RPC$Builder.build(RPC.java:802)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.initIpcServer(DataNode.java:1004)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.startDataNode(DataNode.java:1416)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.<init>(DataNode.java:497)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.makeInstance(DataNode.java:2769)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.instantiateDataNode(DataNode.java:2677)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.createDataNode(DataNode.java:2719)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.secureMain(DataNode.java:2863)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.main(DataNode.java:2887)
Caused by: java.net.BindException: Address already in use
```

I don't really understand this error as i don't see any other process on this port.

Anyway, the default port for `dfs.datanode.address` is 9866 so why change it ?

I don't have the issue if I manually switch back to this with `hdfs_dn_rpc_port: 9866`.

2022-06-03 09:34 UTC, leopaul36 commented
Ok actually port 9867 is the default for `dfs.datanode.ipc.address` so this is why we have this error.

2022-06-03 09:35 UTC, leopaul36 commented on tdp_vars_defaults/hdfs/hdfs.yml
> +hdfs_dn_rpc_port: 9867
```suggestion
hdfs_dn_rpc_port: 9866
```

2022-10-05 12:14 UTC, rpignolet commented on tdp_vars_defaults/hdfs/hdfs.yml
> +  dfs.datanode.data.dir: "{{ hadoop_hdfs_dir }}/dn"
You should not modified this variable, we said that data must be in `/data` and `hadoop_hdfs_dir` are for HDFS working files but not HDFS data files.

2022-10-07 13:37 UTC, kpgtek commented on tdp_vars_defaults/hdfs/hdfs.yml
> +  dfs.datanode.data.dir: "{{ hadoop_hdfs_dir }}/dn"
This is fixed, I should make some confusion when beginning this PR for HDFS data files.

2022-10-07 16:48 UTC, rpignolet approved these changes

2022-10-10 13:31 UTC, rpignolet requested changes
@kpgtek please rebase on master due to #495.

2022-10-12 07:02 UTC, gboutry approved these changes

2022-10-12 08:12 UTC, rpignolet approved these changes

2022-10-13 14:18 UTC, leopaul36 approved these changes

2022-10-14 12:35 UTC, merged