kms: add ranger kms service to tdp-collection
TOSIT-IO/tdp-collection pull request #355
Opened 2022-07-05 16:32 UTC by mehdibn

#### Which issue(s) this PR fixes:

Fixes #354 

This PR adds Ranger KMS service to tdp collection with:
- ranger admin integration for (1) keys and (2) policies management 
- add ssl/tls adequate integration for knox/swebhdfs support 
- full kerberos support 
- solr audit integration 

For test :
 - login to ranger amin with keyadmin creds, (default : keyadmin/RangerKeyAdmin123)
 - create a new key via ranger admin : Encryption -> select service -> kms-tdp -> add new key 
 - add a kms policy for you user via ranger admin : access manager -> kms-tdp
 - connect to edge
 - generate a kerberos token : `kinit`
 - try to list all keys with an authorized user: `hadoop key list`
 - create a new hdfs dir : `hdfs dfs -mkdir /secure`
 - add hdfs ranger policy to this path
 - create an encrypted zone with the generated key: `hdfs crypto -createZone  -keyName <your_generated_key> -path /secure`
 - try to put a file via `hdfs dfs -put /etc/hosts hdfs://mycluster/secrue` or `hdfs dfs -put /etc/hosts swebhdfs://mycluster/secrue`
 - try to read it with different users via the same commands (`hdfs` or `swebhdfs`) or `knox`

#### Additional comments:

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-07-07 09:54 UTC, gboutry requested changes
@mehdibn thank you for your contribution to TDP!

In a fully open-source approach, all Issues/Pull Requests are fairly examined for integration.

Please find in this review some points to address in order to validate your PR before merging to master branch.

While some points must be addressed, some are open interrogations where we can discuss it.

Please note that without your feedback, this issue will be closed in a few days.


Thank you again for your contribution to TDP.

2022-07-07 09:54 UTC, gboutry commented on roles/ranger/kms/tasks/hdfs.yml
> +    remote_src: yes
Why a different task for this ? Shouldn't this kind of tasks be in `ranger_kms_config` ? (with a dependency on `hadoop_client_config`)

Moreover, the core-site path should be templated using:
`{{ hadoop_client_conf_dir }}/core-site.xml`

2022-07-07 09:54 UTC, gboutry commented on roles/ranger/common/tasks/install.yml
> +    owner: '{{ ranger_kms_user }}'
Are this user and this folder needed on every hosts where you install **any** ranger component ? If not, it shouldn't be in common

2022-07-07 09:54 UTC, gboutry commented on roles/ranger/kms/tasks/init.yml
> +        password: keyadmin
Isn't this configurable in other parts of the installation ? If it is, it should be a variable

2022-07-07 09:54 UTC, gboutry commented on roles/ranger/common/templates/kms-site.xml.j2
> +</configuration>
Why is this site.xml fully commited, and not just rendered on deployment like any other site.xml ?

2022-07-07 09:54 UTC, gboutry commented on tdp_lib_dag/ranger.yml
> +    - ranger_kms_config
Can you put this before the service definition, in every other dag definition, we tend to put the service definition last.

2022-07-07 09:54 UTC, gboutry commented on tdp_vars_defaults/hadoop/hadoop.yml
> +  hadoop.proxyuser.knox.users: "*"
```suggestion
  hadoop.proxyuser.knox.users: "*"
```

2022-07-07 09:54 UTC, gboutry commented on tdp_vars_defaults/hadoop/hadoop.yml
> +ranger_kms_url: "kms://https@{{ groups['ranger_kms'][0] | tosit.tdp.access_fqdn(hostvars) }}:9393/kms"
Is it possible to put the port in a variable ? if it's configurable of course.
We're currently working on moving every ports used in variables.

While it's a work in progress in old components, it would be good if new components would directly use this convention.

2022-07-07 09:54 UTC, gboutry commented on tdp_vars_defaults/ranger/ranger.yml
> +ranger_kms_install_dir: "/opt/tdp/ranger-kms"
```suggestion
ranger_usersync_install_dir: "{{ ranger_root_dir }}/ranger-usersync"
ranger_kms_install_dir: "{{ ranger_root_dir }}/ranger-kms"
```

These directories should be templated using the `ranger_root_dir` variable. Can you do it please ?

(It might not be clear why it's done for usersync in this PR, but since you're modifying adjacent variables, you can do it.)

2022-07-12 10:05 UTC, mehdibn commented on roles/ranger/common/tasks/install.yml
> +    owner: '{{ ranger_kms_user }}'
without this, we will have a cyclic graph : `ranger_kerberos_install  -> ranger_kms_install -> ranger_admin_start -> .. >  ranger_kerberos_install`

2022-07-12 10:08 UTC, mehdibn commented on roles/ranger/kms/tasks/init.yml
> +        password: keyadmin
username/password are not used in this context, because, only kerberos is taken into account. Again, i tried to keep the same existing patter: https://github.com/TOSIT-IO/tdp-collection/blob/master/roles/hdfs/ranger/tasks/init.yml

2022-07-12 10:08 UTC, mehdibn commented on roles/ranger/common/templates/kms-site.xml.j2
> +</configuration>
i can't do it as described, because, this config file is generated by ranger scripts

2022-07-12 10:18 UTC, mehdibn commented on tdp_vars_defaults/hadoop/hadoop.yml
> +ranger_kms_url: "kms://https@{{ groups['ranger_kms'][0] | tosit.tdp.access_fqdn(hostvars) }}:9393/kms"
This port is not configurable, as it's automatically generated by the script. Doing it, can induce to error ..

2022-07-12 10:20 UTC, mehdibn commented on tdp_vars_defaults/ranger/ranger.yml
> +ranger_kms_conf_dir: "/etc/kms"
yes, this path is hard-coded in the ranger script :(

2022-07-12 13:45 UTC, gboutry approved these changes

2022-07-19 11:59 UTC, rpignolet commented on roles/hdfs/datanode/tasks/ssl-tls.yml
> +    truststore_location: "/etc/pki/java/cacerts"
Why this string is not a variable ? Same for password.

2022-07-19 12:05 UTC, mehdibn commented on roles/hdfs/datanode/tasks/ssl-tls.yml
> +    truststore_location: "/etc/pki/java/cacerts"
it kept the same code as [knox](https://github.com/TOSIT-IO/tdp-collection/blob/838a77c8f992c2aa23affb7c53ac18262a2b07b0/roles/knox/gateway/tasks/config.yml#L144)

We can open another issue to fix it

2022-07-19 12:07 UTC, rpignolet approved these changes

2022-07-19 12:49 UTC, merged