[WIP] Firewall rules
TOSIT-IO/tdp-collection pull request #452
Opened 2022-09-09 09:51 UTC by Nuttymoon

#### Which issue(s) this PR fixes:

Fixes #422 

#### Additional comments:

**Work in progress:** for now, the firewall rules are only implemented for HDFS DataNode. The goal of this PR for now is to get feedback on the implementation.

The implementation proposed here inherits the concepts of [firewalld](https://firewalld.org/): [zones](https://firewalld.org/documentation/zone/) and [services](https://firewalld.org/documentation/service/). A service corresponds to a list of ports (+protocols) and a zone corresponds to a list of sources (~= IPs) and the rules that apply to them when accessing services on the host.

##### Cluster level firewall

`firewall_enabled` controls if the firewall should be activated on the hosts. If `yes`, TDP ensures that `firewalld` is started. If `no`, the firewall rules are still set on the hosts, but have no effect (as `firewalld` is stopped).

https://github.com/TOSIT-IO/tdp-collection/blob/c21c890bf8dc037f057028d3e549a8b7c4d70c5b/tdp_vars_defaults/all/all.yml#L45

##### Firewall zones

By default, TDP will create 2 zones:

- `tdp_public`: This zone corresponds to all the hosts outside of the TDP cluster that need access to its client endpoints (e.g. HDFS Web UI, Hive JDBC/ODBC).
- `tdp_internal`: This zone corresponds to all the TDP cluster hosts. Internal ports need to be opened inside the cluster.

https://github.com/TOSIT-IO/tdp-collection/blob/c21c890bf8dc037f057028d3e549a8b7c4d70c5b/tdp_vars_defaults/all/all.yml#L47-L55

Each zone has 3 properties:

- `name`: A name for the zone
- `groups`: The Ansible groups that are part of this zone. TDP will take care of mapping these groups to [firewalld ipsets](https://firewalld.org/documentation/ipset/).
- `addresses`: The other addresses that are part of this zone. Can be in the format `address` or `address/mask`.

##### Firewall rules

For each component, open ports rules are listed under `firewall_rules` in its configuration file. E.g. for the `hdfs_dn` (HDFS DataNode) component in `tdp_vars/hdfs/hdfs_dn.yml`:

https://github.com/TOSIT-IO/tdp-collection/blob/c21c890bf8dc037f057028d3e549a8b7c4d70c5b/tdp_vars_defaults/hdfs/hdfs_dn.yml#L6-L19

Each rule has 5 properties:

- `short`: A name for the rule that will be used in the `firewalld` service definition
- `port`: The port to open and secure
- `protocol`: The protocol authorized on this port
- `zone`: The zone to which the port will be added.
- `enabled`: Whether the rule is enabled or not

##### Low level implementation

TDP uses `firewalld` ipsets, services and zones to set firewall rules:

- **Firewalld ipsets:** each Ansible group that is used in `firewall_zones` will be mapped to an ipset in `/etc/firewalld/ipsets`. E.g. `/etc/firewalld/ipsets/tdp_cluster.xml`:

  ```xml
  <?xml version="1.0" encoding="utf-8"?>
  <ipset type="hash:net">
    <short>tdp_cluster Ansible group</short>
    <entry>192.168.56.13</entry>
    ...
    <entry>192.168.56.16</entry>
  </ipset>
  ```

- **Firewalld services:** each TDP component has 1 service (in `/etc/firewalld/services`) for each of its `firewalld_rules`. A service contains the port number and protocol. E.g. `/etc/firewalld/services/hdfs_dn_data_port.xml`:

  ```xml
  <?xml version="1.0" encoding="utf-8"?>
  <service>
    <short>HDFS DataNode data transfer port</short>
    <port protocol="tcp" port="9866" />
  </service>
  ```

- **Firewalld zones:** Each zone in `firewall_zones` has 1 zone in `/etc/firewalld/zones` that defines the sources allowed to the zone's services. E.g. `/etc/firewalld/zones/tdp_internal.xml`:

  ```xml
  <?xml version='1.0' encoding='UTF-8'?>
  <zone>
    <service name="hdfs_dn_data_port"/>
    <service name="hdfs_dn_ipc_port"/>
    ...
    <source ipset="tdp_cluster"/>
  </zone>
  ```

#### License agreement

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-09-14 16:14 UTC, rpignolet requested changes

2022-09-14 16:14 UTC, rpignolet commented on roles/utils/firewall/tasks/firewalld-service-zones.yml
> +  xml:
Why not using template file for zone instead of modifying XML files ?

2022-09-14 16:14 UTC, rpignolet commented on roles/utils/firewall/tasks/firewalld-zones.yml
> +- name: Reload firewalld
Why do you need reload here and at the end of this file ?

2022-09-14 16:14 UTC, rpignolet commented on roles/utils/firewall/templates/firewalld-ipset.xml.j2
> +  <entry>{{ hostvars[host].ansible_host }}</entry>
We use `ansible_fqdn` in many place, I think we should use it as well instead of `ansible_host`.

2022-09-14 16:14 UTC, rpignolet commented on tdp_vars_defaults/hdfs/hdfs_dn.yml
> +    enabled: yes
It is possible to use `state: present` and `state: absent` to add the port or to remove the port respectively ? And if the `state` is missing, it default to `present` to avoid adding a `state` line for every items ?

2022-09-23 12:39 UTC, Nuttymoon commented
Following September 23th call, actions to take:
- Move all firewall rules to `tdp_vars_default/all/all.yml`
- Create a `firewall` service that will be run one time at the beginning of the DAG
- If `firewall_enabled: no` remove all TDP-generated zones, services, and ipsets
- Prefix all TDP-generated `firewalld` XML files by `tdp_`

2022-09-23 12:45 UTC, Nuttymoon commented on tdp_vars_defaults/hdfs/hdfs_dn.yml
> +    enabled: yes
We could rename `enabled` to `state` for more readability

2022-10-03 16:48 UTC, rpignolet commented on roles/utils/firewall/templates/firewalld-ipset.xml.j2
> +  <entry>{{ hostvars[host].ansible_host }}</entry>
I do not see where `ansible_host` is defined, it is a default Ansible fact ? The machines can have multiple IP so we can't rely on the IP provided by Ansible that why, in `tdp-prerequisites`, I added an `ip` variable (https://github.com/TOSIT-IO/tdp-collection-prerequisites#system-configuration) to build `/etc/hosts` file but for now the `ip` variable is not required for `tdp-collection` to work, maybe you will add the need with firewall configuration.

2022-10-04 07:27 UTC, Nuttymoon commented on roles/utils/firewall/templates/firewalld-ipset.xml.j2
> +  <entry>{{ hostvars[host].ansible_host }}</entry>
Yes indeed, I had a chat with @gboutry yesterday, I will use the `ip` variable as `ansible_host` is not always the host IP address (can be localhost or an FQDN). I will add the need for it in the docs.

2022-10-04 12:22 UTC, Nuttymoon commented
Closing this PR for clarity as a lot of code has been refactored. Opening a new one.

2022-10-04 12:22 UTC, closed without merging