cluster_name var  to change the name of cluster
TOSIT-IO/tdp-collection pull request #459
Opened 2022-09-22 19:33 UTC by taabich

#### Which issue(s) this PR fixes:

Fixes #458 

#### Additional comments:

The variable cluster_name ca be used to override the default name "mycluster" of the cluster

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-09-23 14:56 UTC, leopaul36 commented on README.md
> +| `cluster_name` | The default cluster name `mycluster`. |
No need to describe vars in the README for now

2022-09-23 14:58 UTC, leopaul36 commented on docs/developer.md
> +  dfs.nameservices: {{cluster_name | default("cluster_name")}}
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 requested changes
Hello @taabich,

Thanks for your contribution to TDP.

Additionally to my comments, please recommit using [SemVer](https://semver.org/) for commit messages as stated in our [contributing](https://github.com/TOSIT-IO/TDP/blob/main/CONTRIBUTING.md#semantic-versioning) docs.

2022-09-23 15:08 UTC, leopaul36 commented on roles/hdfs/ranger/tasks/init.yml
> +        fs.default.name: hdfs://{{cluster_name |default("cluster_name")}}
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on docs/developer.md
> +  dfs.ha.namenodes.{{cluster_name |default("cluster_name")}}: nn1,nn2
Let's not replace the vars in this static documentation

2022-09-23 15:08 UTC, leopaul36 commented on docs/developer.md
> +... will replace `hdfs_site` completely, removing `dfs.nameservices` and `dfs.ha.namenodes.{{cluster_name}}` from the `hdfs_site` hash.
Let's not replace the vars in this static documentation

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/hadoop/hadoop.yml
> +  fs.defaultFS: "hdfs://{{cluster_name |default('mycluster')}}"
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/hbase/hbase.yml
>    hbase.cluster.distributed: "true"
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/hbase/hbase.yml
> +  audit_hdfs: hdfs://{{cluster_name |default('mycluster')}}
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/hdfs/hdfs.yml
> +  dfs.ha.namenodes.{{cluster_name |default('myclyster')}}: nn1,nn2
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/hdfs/hdfs.yml
> +  dfs.namenode.https-address.{{cluster_name |default('mycluster')}}.nn2: "{{ groups['hdfs_nn'][1] | tosit.tdp.access_fqdn(hostvars) }}:9871"
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/hdfs/hdfs.yml
> +    }}/{{cluster_name |default('mycluster') }}
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/hdfs/hdfs.yml
> +  dfs.client.failover.proxy.provider.{{cluster_name |default('mycluster') }}: org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/hive/hive.yml
> +  audit_hdfs: hdfs://{{cluster_name |default('mycluster') }}
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/knox/knox.yml
> +  audit_hdfs: hdfs://{{cluster_name |default('mycluster')}}
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/spark/spark.yml
> +  spark.eventLog.dir: hdfs://{{cluster_name |default('mycluster') }}/spark-logs
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/spark/spark.yml
> +  spark.history.fs.logDirectory: hdfs://{{cluster_name |default('mycluster')}}/spark-logs
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/spark3/spark3.yml
> +  spark.eventLog.dir: hdfs://{{cluster_name|default('mycluster')}}/spark3-logs
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/spark3/spark3.yml
> +  spark.history.fs.logDirectory: hdfs://{{cluster_name |default('mycluster')}}/spark3-logs
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-23 15:08 UTC, leopaul36 commented on tdp_vars_defaults/yarn/yarn.yml
> +  yarn.resourcemanager.cluster-id: "{{cluster_name |default('mycluster')}}"
Please respect our current conventions by keeping a whitespace before and after every `{{` and `}}`

2022-09-26 06:48 UTC, taabich commented
Hi,
I committed the conventions to respect space before {{ and after }}.
The role of template-plus is to evaluate the variables in the keys of ansible dictionary: Standard templates  can't do it.
Exemple: 
Template Ansible can't evalute fs.namenode.rpc-address.{{ cluster_name | default('mycluster') }}.nn1 but template-plus do it.
hdfs_site:
...
dfs.namenode.rpc-address.{{ cluster_name | default('mycluster') }}.nn1: "{{ groups['hdfs_nn'][0] | tosit.tdp.access_fqdn(hostvars) }}:8020"
...

Best regards

2022-09-26 15:44 UTC, rpignolet commented
I understand the need to template `key` of `dict` inside `tdp_vars` but for me this not the good way to do it. We have a plugin `resolve` which merge and template `tdp_vars`. I think this should be possible to template `key` in the plugin code. If someone proves to me that this is not possible with the plugin, I will think about whether there is another solution.

2022-09-26 20:10 UTC, taabich commented
Hi,
I'd be glad if  evaluating ` keys`  with ansible variable would work. but unfortunately it doesn't work. I tested several times before creating template-plus.
If you prove the pluging `resolve`  its works to evaluated {{ cluster_name | default('mycluster') }} in this case:
dfs.namenode.rpc-address.{{ cluster_name | default('mycluster') }}.nn1: "{{ groups['hdfs_nn'][0] | tosit.tdp.access_fqdn(hostvars) }}:8020"
I would be pleased  to delete template-plus.
Best regards

2022-09-30 13:15 UTC, leopaul36 commented
Created https://github.com/TOSIT-IO/tdp-collection/issues/469 for key name templating support in resolve``

2022-10-05 11:46 UTC, rpignolet commented
@taabich  thank you for your contribution to TDP!
In a fully open-source approach, all Issues/Pull Requests are fairly examined for integration.
Please find below some points to address in order to validate your PR before merging to master branch:
  - `resolve` plugin now support template key with #482, use this feature and remove `template_plus`
  - consider remaining code review comments

Please note that without your feedback, this issue will be closed in a few days.
Thank you again for your contribution to TDP.

2022-10-14 12:40 UTC, leopaul36 commented
@taabich will you be working on this?

2022-10-17 12:16 UTC, taabich commented
Hi! Sorry,
I'm busy at the moement, I would quickly take the resolution of the merge.
Best regards

2022-11-14 10:46 UTC, Nuttymoon commented
Closing as this was fixed by #531

2022-11-14 10:46 UTC, closed without merging