feat(dag): add "tdp-cluster" service
TOSIT-IO/tdp-collection pull request #498
Opened 2022-10-11 08:55 UTC by rpignolet

All components config must depends on the `tdp-cluster` service in order to be restarted if variable from `tdp-cluster` service are updated.

#### Which issue(s) this PR fixes:

Fixes #497 

#### Additional comments:

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-10-11 13:10 UTC, gboutry approved these changes

2022-10-11 13:46 UTC, mehdibn approved these changes

2022-10-11 13:56 UTC, gboutry requested changes
You need to rename the tdp_vars_defaults to `tdp-cluster`, and propagate this change to the resolve plugin.

(If you want to validate the name `tdp-cluster`, which is what we want)

2022-10-12 09:29 UTC, rpignolet commented
> You need to rename the tdp_vars_defaults to `tdp-cluster`, and propagate this change to the resolve plugin.
> 
> (If you want to validate the name `tdp-cluster`, which is what we want)

It is done.

2022-10-12 14:08 UTC, leopaul36 approved these changes

2022-10-12 18:55 UTC, merged