Fix Solr install
TOSIT-IO/tdp-collection pull request #508
Opened 2022-10-17 15:03 UTC by Nuttymoon

#### Which issue(s) this PR fixes:

Fixes:
- #326 
- #426 

#### Additional comments:

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-10-17 15:06 UTC, gboutry requested changes
Can you regenerate the meta playbooks with the command `tdp playbooks` ?

2022-10-17 16:31 UTC, Nuttymoon commented on tdp_lib_dag/ranger.yml
> +    - ranger_admin_start
I agree with @leopaul36 that every service has a soft dependency on Solr. But I do not recall a case where this is fatal.

2022-10-17 16:32 UTC, Nuttymoon commented on tdp_lib_dag/ranger.yml
> +    - ranger_admin_start
As for the `ranger_admin_start`, I thought that Solr needed to communicate with Ranger admin during init but after double checking, it's not the case.

Force pushing to remove the dependency.

2022-10-17 17:01 UTC, rpignolet reviewed
LGTM for Ansible code, for DAG I leave it to the experts

2022-10-18 07:49 UTC, gboutry commented on tdp_lib_dag/ranger.yml
> +    - ranger_admin_start
IMO, we should have the admin depend on solr.
We can depend on something that won't happen (noop, or not in topology). It's not a problem.

But, if we run a deployment with `ranger_admin_init` as target, should we expect solr installed and ready to work with ranger admin or not ?
If the answer is yes, ranger admin must depend on solr.
If the answer is no, ranger admin does not need to depend on solr.

2022-10-18 13:20 UTC, Nuttymoon commented on tdp_lib_dag/ranger.yml
> +    - ranger_admin_start
Works for me. Forced push to make `ranger_admin_start` depend on `ranger_solr_init`

2022-10-18 13:24 UTC, gboutry approved these changes

2022-10-20 13:31 UTC, merged