Apply ansible best practices (priority on owner:group:mode)
TOSIT-IO/tdp-collection pull request #551
Opened 2022-11-22 13:10 UTC by gboutry

#### Which issue(s) this PR fixes

Fixes #546

#### Additional comments

:warning: Tell me if you'd rather PR per service instead of a big PR

- :warning: JMX Password are rendered as `root:root:644`
- This PR tries not to change big behaviors.
- Ranger are chowned to `{ranger_user}:{hadoop_group}` for idempotence

Here are the remaining warnings that would need dedicate PRs:
```yaml
  - command-instead-of-shell  # Use shell only when shell functionality is required
  - deprecated-command-syntax  # Using command rather than an argument to e.g. file
  - experimental  # all rules tagged as experimental
  - no-changed-when  # Commands should not change things if nothing needs doing
  - risky-shell-pipe  # Shells that use pipes should set the pipefail option
  - yaml  # Violations reported by yamllint
```
#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-11-22 17:20 UTC, gboutry commented
Force push is rebase on master

2022-11-23 09:58 UTC, mehdibn approved these changes

2022-11-23 10:17 UTC, mehdibn approved these changes

2022-11-23 11:01 UTC, rpignolet requested changes

2022-11-23 11:05 UTC, gboutry commented on roles/hive/hiveserver2/tasks/jmx-exporter.yml
> +# Copyright 2022 TOSIT.IO755
Solved

2022-11-23 11:06 UTC, gboutry commented on roles/utils/ssl_tls/tasks/convert_cert_key.yml
> +    mode: 0600
Solved in last force pushed

2022-11-23 11:06 UTC, gboutry commented on roles/utils/ssl_tls/tasks/create_keystore.yml
> +    mode: 0640
Solved in last force pushed

2022-11-23 11:06 UTC, gboutry commented on roles/utils/ssl_tls/tasks/create_truststore.yml
> +    mode: 0644
Solved in last force pushed

2022-11-23 11:07 UTC, rpignolet approved these changes

2022-11-23 12:19 UTC, leopaul36 approved these changes
Validated with a fresh `tdp-getting-started` install

2022-11-23 12:21 UTC, merged