hadoop: add httpfs
TOSIT-IO/tdp-collection pull request #619
Opened 2023-01-04 10:06 UTC by nschung

#### Which issue(s) this PR fixes

Fixes #227

#### Additional comments

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-01-04 17:09 UTC, leopaul36 requested changes
I think the PR is missing the meta playbooks regeneration.

Otherwise everything looks good to me!

2023-01-04 18:00 UTC, nschung commented on roles/hdfs/httpfs/tasks/install.yml
> +
Thanks. It has been completed on the last commit.

2023-01-05 08:38 UTC, leopaul36 approved these changes

2023-01-05 10:08 UTC, rpignolet approved these changes

2023-01-06 09:14 UTC, merged