hive: add resources allocation management
TOSIT-IO/tdp-collection pull request #627
Opened 2023-01-05 13:54 UTC by mehdibn

#### Which issue(s) this PR fixes

Fixes #617 

#### Additional comments

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-01-05 14:00 UTC, leopaul36 commented on roles/hive/common/templates/hive-env.sh.j2
> +  export HADOOP_HEAPSIZE={{ hive_hs2_heapsize }}
I think we should move the `m` from line 69 to the variable to have consistency with the other Xmx variables you've implemented before @mehdibn

2023-01-05 14:00 UTC, rpignolet approved these changes

2023-01-05 14:00 UTC, leopaul36 requested changes

2023-01-05 14:00 UTC, leopaul36 commented on roles/hive/common/templates/hive-env.sh.j2
> +  export HADOOP_HEAPSIZE={{ hive_hs2_heapsize }}
I think we should move the `m` from line 69 to the variable to have consistency with the other Xmx variables you've implemented before @mehdibn

2023-01-06 09:45 UTC, mehdibn commented on roles/hive/common/templates/hive-env.sh.j2
> +  export HADOOP_HEAPSIZE={{ hive_hs2_heapsize }}
@leopaul36 i see it, but this var can be also used by this script or other hive ones …

2023-01-10 08:47 UTC, leopaul36 approved these changes

2023-01-10 09:02 UTC, rpignolet approved these changes

2023-01-10 10:18 UTC, merged