feat(tdp_vars_defaults): changes in order tu use phoenix via knox
TOSIT-IO/tdp-collection pull request #894
Opened 2024-11-19 14:16 UTC by alexismarie8314

Hello, 
Please could you merge this PR, it fixes the #893 issue.

Regards

2024-11-19 14:25 UTC, Pierrotws requested changes

2024-11-19 14:25 UTC, Pierrotws commented on tdp_vars_defaults/hbase/hbase.yml
> +  phoenix.queryserver.remoteUserExtractor.param: "doAs"
I guess a comment should specify to NOT change that value, since I don’t think its catched by knox.
So knox will append doAs whatever this value is, hence this property MUST not be changed

2024-11-26 14:23 UTC, alexismarie8314 commented
> Test to do : impersonate as another user from tdp_user and do a request to phoenix queryserver and check it fails. If not this a securty issue since tdp_user is not suppose to impersonate.

I have tried to connect to the phoenix query server by impersonnating hbase from tdp_user and it failed.

2024-12-03 14:08 UTC, Pierrotws approved these changes

2024-12-03 14:08 UTC, merged